# Generated by Django 5.0.2 on 2024-02-18 10:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kafe', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='category_en',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='kafe.category'),
        ),
        migrations.AddField(
            model_name='food',
            name='category_ru',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='kafe.category'),
        ),
        migrations.AddField(
            model_name='food',
            name='description_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='food',
            name='description_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='food',
            name='name_en',
            field=models.CharField(max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='food',
            name='name_ru',
            field=models.CharField(max_length=16, null=True),
        ),
    ]
